package com.bionym.ncl.helper;

enum NclHelperAction{
	DISCOVER_ALL_NYMIS,
	PROVISION,
	CREATESK,
	GET_KEY,
	FIND_ALL_NYMIS,
	FIND_SELECT_NYMI,
	GET_SK_SELECT_NYMI,
	SIGN_SELECT_NYMI,
	GET_ACCEL,
	GET_ECG,
	GET_GYRO,
	GET_GESTURE
}